### PR TITLE
Use text-decoration for underlines

### PR DESCRIPTION
**Pull request by flying-sheep**
Seems like you’re using an ancient hack for some reason.

The better alternative might be to use CSS variables for everything, but that’s a big refactor and this PR is only a small fix.

### CODE REVIEW

**Comment by flying-sheep** [comment]
I’m sorry if that feels contrarian to you but hear me out: I don’t think I’m willing to do that without being notified of that expectation whenever I open a PR.

I contribute to many projects. Other projects have different expectations and e.g. don’t want people to rebase in-progress PRs (they’ll rebase once they’re happy with the PR contents). I’m not going to remember whatever project has which conventions, and I won’t look them up by myself each time.

I have two suggestions. One productive solution would be that if you want a certain convention, set up your CI to complain if they’re not upheld. There’s CI for what you ask for, I’m sure! Otherwise, [PR templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) are a thing, and you could use those to notify people of your expectations.

**Comment by return42** [comment]
>  with unhelpful commit messages. 

I think the issues @davidism addressed are the commit messages and how patches are bundled / logically related changes are packed into a commit.  Clean commits and meaningful commit messages are the base of every version management, this is the same in all projects.

> squash your work commits ..

By example: *bundling of patches*

The commits "Babel", "Jinja" .. are all related to one topic: "use text-decoration for underlines" --> The cardinal rule for creating good commits is to ensure there is only one "logical change" per commit [1].


By example: *commit message* 

>  .. and write descriptive messages.

"jinja" is not a meaningful commit message .. when I scroll along the history .. and came to this point, I have to open the patch to see what this commit does .. a commit message should be expressive so that it is helpful in a later research.

[1] https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes

**Comment by flying-sheep** [comment]
I understand how to clean up a commit history. I’m just not doing that while working on a PR.

As said above: I’m happy to `git rebase -i` when asked to do so, I just won’t do it by default since many projects don’t care at all, and others do a squash&merge.

**Comment by davidism** [comment]
Wow, that was certainly... a reaction. All I was referring to in this case was the one word commit messages, they're not helpful without the context of the commit before them that has a full sentence. Just copy and paste the sentence next time.

**Pull request merged**
