### PR TITLE
Add support for dark theme

### LINKED ISSUE #48: dark mode
I am requesting  a dark mode version of the website and documentation. It's not about my personal style preference. It's a usability issue since I am presently dealing with cataracts.

A dark theme can be easier to read because it reduces light and improves contrast. An alternate solution would be having the ability to change the style.

I want to thank you for Flask. It's incredible.

### PR DESCRIPTION
**Pull request by yuxiaoy1**
This PR provides basic dark theme support, it aims to add a light/dark theme switch on the sidebar area so user can change the theme very handy. It may not be the final version so welcome any suggestions for improvement.

The theme priority is as follows: local storage user choice > system preference > light mode default.

Here are the screenshots for the light/dark theme supported with this PR.

Light theme:
image

Dark theme:
image

Based on this PR, the pallets project would need another PR to update the `docs/conf.py` to include the theme switch on the sidebar area.

Fix #48

### CODE REVIEW

**Comment by davidism** [comment]
This is a great start. However, I'm going to nitpick on my preferences for dark themes since I'll have to look at these a lot. :-)

* Do not make the colors white text on a black background, the high contrast makes it really hard on my eyes. Twitter and GitHub both have "dim" themes that use greys instead.
* Links and other elements must still have color. It seems that everything is monochrome in your screenshot.

What happens if the browser does not support `prefers-color-scheme`? Given all the CSS/JS features you've used, what is the minimum browser support?

**Comment by ThiefMaster** [comment]
+1 on dim instead of total darkness

I think all halfway recent  browsers support these features:

- https://caniuse.com/prefers-color-scheme
- https://caniuse.com/css-variables

**Comment by yuxiaoy1** [comment]
Hello, @davidism, it's not all monochrome, it has a color when hovering.
The latest color schema is as follows, seems better?

image

And as @ThiefMaster commented, halfway recent browsers support the CSS/JS features.

For the icons, I downloaded them from <https://iconfont.cn>, which is ok if we use them not for commercial purposes, so I think no license is needed.

**Comment by yuxiaoy1** [comment]
@davidism @ThiefMaster Any thoughts?

**Comment by greyli** [comment]
Very cool!

> The latest 2 color schemas are as follows, which one do you suggest?

Personally, I prefer the first color scheme. But maybe the second one is more healthier for eyes.

**Comment by ThiefMaster** [comment]
I prefer the second one over the completely black one.

**Comment by davidism** [comment]
The second one for me as well, the grey is easier for me to read against.

**Comment by flying-sheep** [comment]
Hi, unfortunately this is not complete. There’s no way to reset it to automatic mode.

I fixed that same issue in https://github.com/python/peps/pull/2552, feel free to draw inspiration from that one.

**Comment by davidism** [comment]
Thanks for working on this. We've decided to start using Furo as a base theme, and it provides dark mode.

**Pull request closed without merging**
